version: '3'

services:
  nodeserver:
    build: 
      context: ./nodejs
    container_name: app
    networks:
      - node-network
    tty: true

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "8080:80"
    networks:
      - node-network      

networks:
  node-network:
    driver: bridge